### ISSUE TITLE
rust folder as a rust workspace

### ISSUE THREAD

**Issue by jcajka** [ibm-s390-linux/s390-tools#156]
I would like to ask if rust folder with collection of crates can be made back to the rust workspace. Due to new approaches of the Fedora's rust packaging folks it would greatly ease and simplify packaging there along with IMHO easier vendoring handling.

**Comment by steffen-eiden** [comment]
IMO we can do this.
If I am not mistaken @xnox wanted us to not use workspaces. Is that still the case?

If nothing stands against using workspaces I would add `rust/Cargo.toml` with the following content:

```toml
[workspace]

members = [
    "pv",
    "pvsecret",
    "utils",
]

[profile.release]
lto = true
panic = "abort"
``` 
In difference to the workspace from the POC I would not define dependencies here, but in the workspace members scope.

With this minimal definition one could just remove the new Cargo.toml and still  be able to compile all the tools.

CC: @sharkcz  @frank-heimes @ngueorguiev @hoeppnerj
